### ISSUE TITLE
Crash on loading scene

### ISSUE THREAD

**Issue by varomix** [UnderwaterApps/overlap2d-runtime-haxeflixel#1]
Hi
I just found out about Overlap2D, what an amazing application, thank you for sharing it.
I use HaxeFlixel and wanted to try it there but the game crashes after going to the MenuState

HaxeFlixel 4 was released recently so maybe something changed
please help I would love to use this for my games

Thanks again

Here's the error

> Invalid operation (*)
> Called from overlap2d/CompositeItem.hx line 81
> Called from overlap2d/CompositeItem.hx line 120
> Called from overlap2d/CompositeItem.hx line 53
> Called from overlap2d/CompositeItem.hx line 35
> Called from a C function
> Called from overlap2d/CompositeItem.hx line 7
> Called from overlap2d/SceneLoader.hx line 32
> Called from MenuState.hx line 16
> Called from flixel/FlxGame.hx line 621
> Called from flixel/FlxGame.hx line 706
> Called from flixel/FlxGame.hx line 686
> Called from flixel/FlxGame.hx line 528
> Called from openfl/_legacy/events/EventDispatcher.hx line 98
> Called from a C function
> Called from openfl/_legacy/display/DisplayObject.hx line 161
> Called from a C function
> Called from openfl/_legacy/display/DisplayObjectContainer.hx line 286
> Called from openfl/_legacy/display/Stage.hx line 1103
> Called from openfl/_legacy/display/Stage.hx line 351
> Called from openfl/_legacy/display/Stage.hx line 1084
> Called from openfl/_legacy/display/Stage.hx line 430
> AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by varomix** [comment]
Ok I know what the issue is
the Pixels Per World Unit is missing in the export file
so this:

``` javascript
pixelsPerWU = ir.getProjectVO().pixelToWorld;
```

returns null

`ir.getProjectVO()`
returns this,

> { originalResolution => { name => orig, width => 600, height => 480 }, scenes => [{ physicsPropertiesVO => {}, sceneName => MainScene }] }

 there's no pixelToWorld property there
overlap2D is not exporting that, I even checked the sample project included
and is not there either.

so that is missing, if I set pixelsPerWU to be 1 in CompositeItem.hx line 32
everything work, BUT, that no correct.

I guess the overlap2D exporter needs to be fixed

hope that helps

**Comment by azakhary** [comment]
which version of editor are you using?

**Comment by azakhary** [comment]
have you downloaded 0.1.2 from the website main page?

**Comment by varomix** [comment]
yes that's the version I have, got it from the main site

thanks

**Comment by azakhary** [comment]
oh got it, it might be the case that pixelToWorld was 1, and editor's JSON default value is 1, and due to JSON optimization setting, it is basically removing values that are default.. And this fails in other runtime as it does have different JSON mechanism. now I got it. Thanks for reporting this! the temp fix maybe to put a check in this runtime and if it's missing, set value to one. if you want to do a PR let me know, otherwise I'll do it myself.

**Comment by azakhary** [comment]
fixed in #2
